= Proteus out

== Summary

=== Informasi Umum

Proteus Out Sepulsa adalah _Client Terminal Project_ untuk Serpul (Server) yang digunakan untuk melayani pelanggan yang ingin terhubung dari Serpul Alterra ke Serpul lain seperti IRS, FM, OTOMAX, TIGER.
Dengan kata lain, Proteus Out merupakan jembatan dari sistem Gajah Mada ke layanan _biller_ di tempat lain untuk mengambil stok produk digital seperti pulsa dengan beberapa variasi harga (pulsa nasional atau tradisional).

== Anggota Tim Proteus Out

|===
| Posisi | Nama | Tim

| Product Owner
| Leo Himawan Adiakso
| Putterfish

| Development Manager
| Evan Sujanto
| Putterfish

| Lead Software Engineer
| Kevin Setiawan Tanzil
| Putterfish

| Lead Quality Engineer
| Fransiska Maya
| Pangolin

| Lead System Analyst
| Fiqri Aulia Rahman
| Strix
|===

== Informasi Teknis

<<proteus-out/url-proteus-out.adoc#, System URL Proteus Out>>

<<proteus-out/architecture-proteus-out.adoc#, Architecture Proteus Out>>

<<proteus-out/technology-proteus-out.adoc#, Technology Proteus Out>>

<<proteus-out/environment-proteus-out.adoc#, Environment Proteus Out>>

<<proteus-out/database-proteus-out.adoc#, Database Documentation Proteus Out>>

<<proteus-out/release-deploy-proteus-out.adoc#, Release and Deployment Proteus Out>>


== *Onboarding Information*

<<proteus-out/dev-onboarding-proteus-out.adoc#, Developer Onboarding Proteus Out>>

== *Dokumentasi*

<<proteus-out/api-doc-proteus-out.adoc#, API Documentation Proteus Out>>

<<proteus-out/release-note-proteus-out.adoc#, Release Note Proteus Out>>
