name: Confluence Publisher               

on:
  push:
     tags: 
       - 'v*-traditional'                         
jobs:
    build:
  
      runs-on: ubuntu-latest              
  
      steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK 1.8              
        uses: actions/setup-java@v1       
        with:
          java-version: 1.8               
      - name: Build with Maven
        env:
          username: ${{ secrets.USERNAME_ANIN }}
          password: ${{ secrets.PASSWORD_ANIN }}
        run: mvn org.sahli.asciidoc.confluence.publisher:asciidoc-confluence-publisher-maven-plugin:publish --file pom-proteus-out.xml -Dusername=$username -Dpassword=$password
