name: Confluence Publisher                #penamaan untuk judul pada github action. bisa diisi apasaja

on:
  push:
     tags: 
       - 'v*-bpa'                         #triger untuk menjalankan github action. ini menggunakan tag pada release. "-bpa" dapat difanti apasaja.
jobs:
    build:
  
      runs-on: ubuntu-latest              #paten
  
      steps:
      - uses: actions/checkout@v2         #paten
      - name: Set up JDK 1.8              #paten
        uses: actions/setup-java@v1       #paten
        with:
          java-version: 1.8               #paten
      - name: Build with Maven
        env:
          username: ${{ secrets.username_anin}}
          password: ${{ secrets.password_anin}}
        run: mvn org.sahli.asciidoc.confluence.publisher:asciidoc-confluence-publisher-maven-plugin:publish --file pom-proteus-out.xml -Dusername=$username -Dpassword=$password
        # "--file pom.xml" tergantung tempat peletakan contoh di dalam dokumen "--file nama-document/pom.xml". dan juga penamaan pom dapat ditambahi untuk dokumen yang ingin di publish dalam confluence.
